Update LICENSE
web3community/brand-assets pull request #10
Opened 2021-11-05 14:48 UTC by krishguptadev

Fixes #9

2021-11-05 17:31 UTC, Panquesito7 requested changes

2021-11-05 17:31 UTC, Panquesito7 commented on LICENSE
> +<a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-nd/4.0/88x31.png" /></a
I think we should use the CC-BY-ND 4.0 license (see https://github.com/web3community/brand-assets/issues/9#issuecomment-962076546)
```suggestion
Attribution-NoDerivatives 4.0 International (CC BY-ND 4.0)
Copyright (C) 2021 Web3Community

You are free to:
Share — copy and redistribute the material in any medium or format
for any purpose, even commercially.

Under the following terms:
Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.

NoDerivatives — If you remix, transform, or build upon the material, you may not distribute the modified material.

Notices:

You do not have to comply with the license for elements of the material in the public domain or where your use is permitted by an applicable exception or limitation.
No warranties are given. The license may not give you all of the permissions necessary for your intended use. For example, other rights such as publicity, privacy, or moral rights may limit how you use the material.

For more details:
https://creativecommons.org/licenses/by-nd/4.0/
```

2021-11-06 17:04 UTC, shuklaritvik06 approved these changes

2021-11-06 17:25 UTC, vinzvinci approved these changes

2021-11-06 17:52 UTC, merged

2021-11-07 01:24 UTC, Panquesito7 reviewed
Awesome! LGTM. 🚀